name: macOS Desktop (noVNC)

on:
  workflow_dispatch:

jobs:
  desktop:
    runs-on: macos-latest
    timeout-minutes: 360  # max 6 saat

    steps:
      - name: Install Homebrew & packages (no GUI deps)
        shell: bash
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          eval "$($(which brew || echo /opt/homebrew/bin/brew) shellenv)"
          brew install tiger-vnc xterm git
          # PEP 668 (externally-managed) sebebiyle websockify'i venv'e kuracağız
          python3 -m venv "$HOME/.venv"
          source "$HOME/.venv/bin/activate"
          pip install --upgrade pip
          pip install websockify
          # noVNC brew'de yok; repo'dan klonla
          git clone https://github.com/novnc/noVNC.git "$HOME/noVNC"
          # Cloudflared (Apple Silicon)
          curl -fsSL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-darwin-arm64.tgz -o cloudflared.tgz
          tar -xzf cloudflared.tgz
          chmod +x cloudflared

      - name: Configure VNC
        shell: bash
        run: |
          mkdir -p "$HOME/.vnc"
          echo "test123" | /opt/homebrew/bin/vncpasswd -f > "$HOME/.vnc/passwd"
          chmod 600 "$HOME/.vnc/passwd"
          cat > "$HOME/.vnc/xstartup" <<'EOF'
          #!/bin/sh
          unset SESSION_MANAGER
          unset DBUS_SESSION_BUS_ADDRESS
          xterm &
          EOF
          chmod +x "$HOME/.vnc/xstartup"

      - name: Start VNC and noVNC
        shell: bash
        run: |
          eval "$($(which brew || echo /opt/homebrew/bin/brew) shellenv)"
          /opt/homebrew/bin/vncserver :1 -geometry 1920x1080 -depth 24 -localhost yes
          # venv içindeki websockify ile noVNC'yi sun
          "$HOME/.venv/bin/python" -m websockify --web="$HOME/noVNC" 6080 localhost:5901 > novnc.log 2>&1 &

      - name: Start Cloudflare Tunnel
        id: tunnel
        shell: bash
        run: |
          ./cloudflared tunnel --url http://localhost:6080 --no-autoupdate > cfd.log 2>&1 &
          for i in $(seq 1 30); do
            URL=$(grep -oE 'https://[a-z0-9-]+\.trycloudflare\.com' cfd.log | tail -n1 || true)
            if [ -n "$URL" ]; then
              echo "url=$URL" >> $GITHUB_OUTPUT
              break
            fi
            sleep 2
          done
          [ -n "$URL" ] || { echo "Cloudflared URL bulunamadı"; tail -n +1 cfd.log; exit 1; }

      - name: Show Connection Info
        shell: bash
        run: |
          echo "## Web macOS Desktop (noVNC)" >> $GITHUB_STEP_SUMMARY
          echo "URL: ${{ steps.tunnel.outputs.url }}/vnc.html" >> $GITHUB_STEP_SUMMARY
          echo "Password: test123" >> $GITHUB_STEP_SUMMARY
          echo "Not: Bu oturum workflow bitene kadar (max 6 saat) açık kalır." >> $GITHUB_STEP_SUMMARY

      - name: Keep session alive
        shell: bash
        run: sleep 21600
